# Generated by Django 4.2.6 on 2023-10-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('type', models.CharField(choices=[('News', 'Новость'), ('Another', 'Другое')], default='News', max_length=50, verbose_name='Тип')),
                ('character', models.TextField(max_length=100, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'список новостей',
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('number', models.CharField(max_length=150, verbose_name='Номер телефона')),
                ('message', models.CharField(max_length=200, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'Записи',
                'db_table': 'record',
            },
        ),
    ]
