# Generated by Django 5.1.1 on 2024-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название трансляции')),
                ('character', models.TextField(max_length=100, verbose_name='Описание трансляции')),
                ('video', models.FileField(upload_to='', verbose_name='Трансляция')),
            ],
            options={
                'verbose_name': 'Трансляция',
                'verbose_name_plural': 'Трансляции',
                'db_table': 'stream',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('about', 'О нас'), ('sponsor', 'Реклама'), ('news', 'Новость'), ('popular', 'Популярное'), ('archive', 'Архивировано')], default='news', max_length=50, verbose_name='Тип'),
        ),
    ]
