# Generated by Django 5.1.1 on 2024-09-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_stream_alter_products_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='video',
            field=models.FileField(upload_to='video/', verbose_name='Трансляция'),
        ),
    ]
