# Generated by Django 5.1.1 on 2024-09-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_record_timeposted_record_user_alter_record_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
