# Generated by Django 5.1.1 on 2024-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_productlike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
