# Generated by Django 5.1.1 on 2024-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_stream_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('about', 'О нас'), ('sponsor', 'Реклама'), ('news', 'Новость'), ('archive', 'Архивировано')], default='news', max_length=50, verbose_name='Тип'),
        ),
    ]
